"""add_first_user

Revision ID: 11e98221d83d
Revises: 6b5ccfe01b47
Create Date: 2020-01-28 11:57:58.613817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e98221d83d'
down_revision = '6b5ccfe01b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
