"""Add a column

Revision ID: ae4f79955418
Revises: a2dd8f960875
Create Date: 2020-08-10 12:49:42.880532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4f79955418'
down_revision = 'b9f6fa363597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('status_code', sa.Integer))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'status_code')
    # ### end Alembic commands ###
